### ISSUE TITLE
Antivirus and chrome flagging the latest zip

### ISSUE THREAD

**Issue by benjaminmills15** [a-sync/audio-router#10]
Could be a false positive because of the DLL files.

**Comment by a-sync** [comment]
It definitely is. :)
Could you please add what antivirus sw your using for reference?

**Comment by crumpetcrusher** [comment]
Microsoft Windows Defender is flagging do.exe as Trojan:Win32/Fuery.B!cl as of 2/3/2019.

**Comment by a-sync** [comment]
@crumpetcrusher make sure you download the release from: https://github.com/a-sync/audio-router/releases 
it's built from the latest #master source, but you can build it yourself if you want to ofc
probably a false positive

**Comment by crumpetcrusher** [comment]
I did, just adding info to the issue.

**Comment by a-sync** [comment]
Thanks :)
