### ISSUE TITLE
VirusTotal warning

### ISSUE THREAD

**Issue by PecceG2** [a-sync/audio-router#12]
Good morning, this software is returning an analysis of Trojans within the analysis in VirusTotal, with av's: McAfee, Sophos, cylance, Ad-Aware, SentinelOne and more.
Please review it and if it is false-positive, report it.
Thanks!

[bootstrapper.dll](https://www.virustotal.com/gui/file/076248ee0770d4e9b393e6c45cbb9f03a6d6fbac76f3e6c890f6469f69c9cd73/detection)
[bootstrapper64.dll](https://www.virustotal.com/gui/file/aa1d8855e6f180b0e6b432efdc377904264452378716d7452ebb1224b40289d9/detection)
[do64.exe](https://www.virustotal.com/gui/file/ba3e0d46604193213e79866da68c24b6ad9d9478653a011056ac51bc6e906779/detection)
[do.exe](https://www.virustotal.com/gui/file/ef874c8516dbcfe4a1bd55f1adf804c59f3d1a654e38902ffb764168b6711835/detection)
[audio-router.dll](https://www.virustotal.com/gui/file/4c06c3da386c9543402439c3a555b4ca68ce6d4127c8b02222b81e5e3b48e6b0/detection)

**Comment by a-sync** [comment]
Thanks for the heads up, but those are false positives.  
They relate to the method audio-router uses to manage different sources.

You're welcome to inspect the source, and build it yourself.
